/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package groupProject2;
import java.io.File;
import java.sql.Connection;
import java.util.List;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;




// mysql -u root -p
// SHOW DATABASES;

public class App extends Application{

    public static String url = "jdbc:mysql://localhost:3306/a2";
    public static String username = "root";
    public static String password = "Abigale1007+120900";
    private static Connection connection;
    static DataBaseMethod dbm = new DataBaseMethod();


    @Override
    public void start(Stage primaryStage) {

        MainPage mainPage = new MainPage();
        Scene mainScene = mainPage.createMainScene(primaryStage);

        primaryStage.setScene(mainScene);
        primaryStage.show();

    }


    public static void main(String[] args) {


//        System.out.println(row.get(0));
        launch();
    }
}
