/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package groupProject2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.*;
import java.util.NoSuchElementException;



class AppTest {

  


}

